AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AGPY project

Resources:
  Items:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Role: arn:aws:iam::760316288087:role/agpy-lambda-role
      Events:
        ListItems:
          Type: Api
          Properties:
            Path: /items
            Method: get
        CreateItem:
          Type: Api
          Properties:
            Path: /items
            Method: post
        GetItem:
          Type: Api
          Properties:
            Path: /items/{item}
            Method: get
        UpdateItem:
          Type: Api
          Properties:
            Path: /items/{item}
            Method: put
        DeleteItem:
          Type: Api
          Properties:
            Path: /items/{item}
            Method: delete
        Invalid:
          Type: Api
          Properties:
            Path: /items/{item}
            Method: any
